### ISSUE TITLE
Compilation terminated.

### ISSUE THREAD

**Issue by huchunjun425** [codeslake/PVDNet#12]
D:\Anaconda3\envs\PVDNet\python.exe E:/code/python/PVDNet/run.py
Laoding Config for evaluation
	Project : PVDNet_TOG2021
	Mode : PVDNet_DVD
	Config: config_PVDNet
	Network: PVDNet
	Trainer: trainer
Loading Model...
	initializing deblurring network
Traceback (most recent call last):
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\cupy\cuda\compiler.py", line 685, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 141, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 153, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 69, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/code/python/PVDNet/run.py", line 347, in <module>
    eval(config)
  File "E:\code\python\PVDNet\eval.py", line 198, in eval
    eval_quan_qual(config)
  File "E:\code\python\PVDNet\eval.py", line 68, in eval_quan_qual
    blur_folder_path_list, blur_file_path_list, gt_file_path_list = init(config, mode)
  File "E:\code\python\PVDNet\eval.py", line 43, in init
    model = create_model(config)
  File "E:\code\python\PVDNet\models\__init__.py", line 5, in create_model
    model = lib.Model(config)
  File "E:\code\python\PVDNet\models\trainers\trainer.py", line 44, in __init__
    Macs,params = get_model_complexity_info(self.network, (1, 3, 720, 1280), input_constructor = self.network.input_constructor, as_strings=False,print_per_layer_stat=config.is_verbose)
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\ptflops\flops_counter.py", line 34, in get_model_complexity_info
    _ = flops_model(**input)
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\torch\nn\modules\module.py", line 1148, in _call_impl
    result = forward_call(*input, **kwargs)
  File "E:\code\python\PVDNet\models\trainers\trainer.py", line 304, in forward
    w_bb = upsample(self.BIMNet(norm(I_curr_refined ), norm(I_prev_refined )), refine_h, refine_w)
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\code\python\PVDNet\models\archs\liteFlowNet.py", line 246, in forward
    tensorFlow = self.moduleMatching[intLevel](tensorFirst[intLevel], tensorSecond[intLevel], tensorFeaturesFirst[intLevel], tensorFeaturesSecond[intLevel], tensorFlow)
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\code\python\PVDNet\models\archs\liteFlowNet.py", line 118, in forward
    tensorCorrelation = torch.nn.functional.leaky_relu(input=FunctionCorrelation(tensorFirst=tensorFeaturesFirst, tensorSecond=tensorFeaturesSecond, intStride=1), negative_slope=0.1, inplace=False)
  File "E:\code\python\PVDNet\models\archs\torch_correlation_C11.py", line 403, in FunctionCorrelation
    return _FunctionCorrelation.apply(tensorFirst, tensorSecond, intStride)
  File "E:\code\python\PVDNet\models\archs\torch_correlation_C11.py", line 300, in forward
    cupy_launch('kernel_Correlation_rearrange', cupy_kernel('kernel_Correlation_rearrange', {
  File "cupy\_core\raw.pyx", line 89, in cupy._core.raw.RawKernel.__call__
  File "cupy\_core\raw.pyx", line 96, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy\_core\raw.pyx", line 113, in cupy._core.raw.RawKernel._kernel
  File "cupy\_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "cupy\_core\raw.pyx", line 547, in cupy._core.raw._get_raw_module
  File "cupy\_core\core.pyx", line 2081, in cupy._core.core.compile_with_cache
  File "cupy\_core\core.pyx", line 2141, in cupy._core.core.compile_with_cache
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\cupy\cuda\compiler.py", line 492, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\cupy\cuda\compiler.py", line 570, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\cupy\cuda\compiler.py", line 321, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\cupy\cuda\compiler.py", line 305, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "D:\Anaconda3\envs\PVDNet\lib\site-packages\cupy\cuda\compiler.py", line 704, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: Catastrophic error: cannot open source file "C:\Users\鑳℃烦淇奬AppData\Local\Temp\tmprv5reuna\d0f546e6b437468d05490e1069adb24672c7985b.cubin.cu"

1 catastrophic error detected in the compilation of "C:\Users\.....\AppData\Local\Temp\tmprv5reuna\d0f546e6b437468d05490e1069adb24672c7985b.cubin.cu".
Compilation terminated.

**Comment by codeslake** [comment]
Try running code in Ubuntu.
I've never tried it in Windows.
